### ISSUE TITLE
Outreach: email template for supporting the "National Police Misconduct Database"

### ISSUE THREAD

**Issue by hcharley** [Police-Data-Accessibility-Project/planning#109]
# Suggestion

We could create an email template supporting the National Police Misconduct Database

# Slack links

[Suggested here](https://policeaccessibility.slack.com/archives/C014X1CQ63B/p1591671300479300)

[The file I started in Slack](https://policeaccessibility.slack.com/files/T013XAUV9GS/F015ER471C1?origin_team=T013XAUV9GS)

# Inspiration 

https://www.vice.com/en_us/article/889gva/defund12-tool-emails-city-councilmembers-with-one-click

https://defund12.org/nyc

# Help needed

The outreach, recognition, and copywriting teams can help.

# Template 

```
To: [AUTOMATICALLY POPULATE RELEVANT CONGRESS PEOPLE]

Subject: [*** INSERT UNIQUE SUBJECT LINE ***]

Message:

Dear Representatives,

My name is [YOUR NAME] and I am a resident of [CITY/TOWN/DISTRICT]. I am writing to you in support of the National Police Misconduct Database introduced in [TBD].

[TODO: WRITE REQUEST FOR THEM TO SUPPORT BILL AS WELL]

[TODO: EXPLAIN WHY THE BILL IS IMPORTANT]

[TODO: ]

Thank you, 
[YOUR NAME]
[YOUR ADDRESS]
[YOUR EMAIL]
[YOUR PHONE NUMBER]
```

**Comment by faithlierheimer** [comment]
Definitely like this idea. I can help write the copy for the email--been helping with some copywriting for the recognition team so I'd be happy to help draft here.

**Comment by charlex** [comment]
@stephharris @faithlierheimer Right now I think probably the best way to move forward is for us to branch this out into a repo outside of PDAP. PDAP leadership is still in the the process of standing up a 501c, so its not yet clear how much of this work will be in scope to the official org.

If I started it in a GH org, are there any name suggestions for it?

**Comment by stephharris** [comment]
Hey @charlex! Sorry, just saw this - NextJS has free hosting via Zeit (now named Vercel as of last month - they recently updated the project). I believe we can do server side rendering and/or static generation, depending on what we want to do - it's all fairly straight-forward through github. I have a bit of experience using the platform so I could definitely help with the scaffolding & steps to deploy. :) https://vercel.com/docs

To your point, could also definitely see this being a simple html page (sans React) using Jekyll or Github Pages or another service to host (although not 100% if it's free to use a custom domain with those?).
