### ISSUE TITLE
Obtain legal counsel

### ISSUE THREAD

**Issue by csa-goose** [Police-Data-Accessibility-Project/planning#11]
Please use this issue to discuss obtaining legal counsel and the risks associated with the groups activities.

**Comment by Fehiroh** [comment]
A friend of a friend set up this resource for getting law students and organizations in touch with one another. https ://www.lawlinks.org/ . 

I think it's primarily Canadian, but I'm in contact with a few lawyer friends, and will update when I get more information.

**Comment by dongately** [comment]
update for the record - @ktynski has progress on pro-bono support as well
