### ISSUE TITLE
Update text that suggests this repo is where code resides

### ISSUE THREAD

**Issue by OscarVanL** [Police-Data-Accessibility-Project/planning#116]
Since we opted to switch from a mono-repo project to a multi-repo project, code related to scrapers has moved to `Police-Data-Accessibility-Project/Scrapers`. 

In light of this, some text has become inaccurate, such as:

![image](https://user-images.githubusercontent.com/7999692/84448995-1519fe00-ac44-11ea-8016-42409119ae84.png)

This repository now seems to primarily consist of organisation and meeting minutes.

**Comment by faithlierheimer** [comment]
Agreed, it's not clear that this is primarily an organizational repo.
