### ISSUE TITLE
Define formal requirements for MVP

### ISSUE THREAD

**Issue by csa-goose** [Police-Data-Accessibility-Project/planning#13]
I have picked up bits and pieces but let's start this thread to define the requirements of what we are building.

**Comment by csa-goose** [comment]
The first set of loose requirements have come from the management team:

> Our product is a consolidated, publicly available library of law enforcement related records. Our goal is to ease data consumption, facilitate open source software analytics, and provide an interface for reporting and analysis of law enforcement activity. Our product will be made publicly available, free of charge.

Broken out, I hear:

- [ ] Publicly available data sets
- [ ] Easy to access and use
- [ ] Reporting and analytics interface(s)

We need clarity on the 3rd bullet. APIs vs a web app, etc...

**Comment by shredinger137** [comment]
That sounds to me like API _and_ web app to me. You need an API to make a web app anyway, and a portal to use the API for non-technical folks would probably be started here anyway.

**Comment by Astaltine** [comment]
Well designed APIs open the door to other interesting and useful tooling to be built on top of our data-set. It can help data scientists or reporters not directly involved with our organization to build interesting insight.

I kind of think some of this comes down to us needing to decide on what our value is. 

Is the data we're collecting where we're adding value? Or are we aiming to provide value by providing high-quality insight to the data we provide?
