### ISSUE TITLE
Patreon/Support/Donations

### ISSUE THREAD

**Issue by dspoka** [Police-Data-Accessibility-Project/planning#53]
Great initiative!

Just wanted to suggest some sort of way people could sponsor any of the compute/api/etc cost to help support this.

**Comment by Astaltine** [comment]
It'd be good to get legal opinions on this before we set something up. It sounds like we've been thinking about making a non-profit org, and they can have strict financing rules.

**Comment by tylercamp** [comment]
Would be appropriate to move this to: https://github.com/Police-Data-Accessibility-Project/organizational-issues

Some related existing issues:

- https://github.com/Police-Data-Accessibility-Project/organizational-issues/issues/11
- https://github.com/Police-Data-Accessibility-Project/organizational-issues/issues/27
