### ISSUE TITLE
Extract PDF Text from Bay County Florida docket attachments

### ISSUE THREAD

**Issue by OscarVanL** [Police-Data-Accessibility-Project/planning#56]
I made a scraper for Bay County Florida in https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project/issues/15, this was merged in https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project/pull/50. One limitation is that Bay County Florida do not show many of the [minimum scraped fields requirements](https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project#the-fields-we-would-like-to-make-sure-to-collect-at-a-minimum-from-any-scrape-are) on their portal. Instead, these are embedded in PDFs attachments in the case dockets.

My scraper downloads these and appends the case number to the beginning. Eg: **`20000113`**`-CASE FILED 01102020 CASE NUMBER 20000113CFMA.pdf`

Here's an example case filing PDF. The blue fields contain the arrest date, arresting officer, officer ID, and DOB, all of which are missing from the scraped data at present. The forms are typed, not hand-written, but **text is not embedded as a textbox, but a image/scan of the printed form**.
<img src="https://user-images.githubusercontent.com/7999692/83638683-6cafce00-a5a1-11ea-8082-1ff4acad6c2a.png" width="50%">

By extracting these fields the scraped data will be more complete.
This would require the following:
1. Classify scraped PDFs into form types
2. Get data from desired parts of the form using OCR/template matching/other technique
3. Update fields in scrapped CSV with this new data

I have no experience scraping data from PDFs, some people with experience doing this have discussed this briefly in Slack. Feel free to take on this task or private message me (Oscar) if you are willing to lend advice.

**Comment by Fehiroh** [comment]
Hey, Oscar, I'd be happy to look into this! Where are your pdfs currently being stored?

**Comment by Fehiroh** [comment]
Thanks! My current computer is a bit temperamental, and is severely limited in terms of harddrive space. I'll attempt the scrape, but I'm already guessing that it'll have issues with installing the prerequisites.  With all of that in mind, samples would be greatly appreciated, as it lets me just dive right into it.

**Comment by OscarVanL** [comment]
Are you in the Slack Group? If so, what's your name?

**Comment by Fehiroh** [comment]
I am. Name is AF :)
