### ISSUE TITLE
Compile a list of counties using Tyler Technologies based systems

### ISSUE THREAD

**Issue by OscarVanL** [Police-Data-Accessibility-Project/planning#6]
To build a generalised scraper that works on Tyler Technologies outsourced court record portals (or other widely used portal systems), it would be a good first step to know which counties use which portal system.

*  What are the obvious indicators of a Tyler Technologies portal?
    So far I've observed Calaveras Superior's domain (cacalaverasportal.tylerhost.net) has tylerhost in its name, though this is not the case for all Tyler Technologies portals.
    The bottom right of the page has an "Empowered by Tyler Technologies" logo.
    The bottom left of the page says '© 2020 Tyler Technologies, Inc.'.

*  Where should this list be compiled?
    I propose adding an extra column to [Privacy_Public Access to Court Records State Links.csv](https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project/blob/master/Privacy_Public%20Access%20to%20Court%20Records%20State%20Links.csv) detailing each portal's vendor.

**Comment by ktynski** [comment]
I like the idea of updating that csv. lets do that.  Alternatively, make it a google doc for collaboration more easily?

**Comment by OscarVanL** [comment]
A Google Doc would be good as it's probably going to take a lot of collaborative work to compile a list of every state and police county, as well as their court portals.

**Comment by ktynski** [comment]
Ok cool, would you be able to move it to a google doc and update the repo?

**Comment by OscarVanL** [comment]
The Google doc wouldn't automatically update the repo, if that's what you mean.

Also, Google sheets would be more suitable for collaborating on it as it keeps the cell-formatting.

We can update the readme with a link to a Google Sheet, then periodically copy the content from the Google sheets and update the GitHub copy.

**Comment by OscarVanL** [comment]
[Here's the Google Sheet](https://docs.google.com/spreadsheets/d/1nD4LnjU1b1b9RgQNcn6op-Oj3ZQVcgz-2bUgEU5RVXA/edit?usp=sharing). I have created this with 'Can Comment' permissions so it does not get vandalised. In its current state I have to approve each edit, full-edit permissions will need to be given to appropriate people.

**Comment by sid137** [comment]
For identifying the sites, one simple approach is Google.  TylerTech is a branded application, so they include their info on every portal:  https://share.getcloudapp.com/bLueXZjd

A starting point would be a basic google search excluding their site

https://www.google.com/search?biw=1544&bih=828&sxsrf=ALeKk00RCf5jbYW05ZiL9VIz_goFlv_ArQ%3A1590802910639&ei=3rnRXtzHJo6TlwSokpuwBA&q=%22%C2%A9+2020+Tyler+Technologies%2C+Inc.%22+-site%3Atylertech.com&oq=%22%C2%A9+2020+Tyler+Technologies%2C+Inc.%22+-site%3Atylertech.com&gs_lcp=CgZwc3ktYWIQAzoECAAQR1CWlAJYlpQCYO2YAmgAcAF4AIABLYgBLZIBATGYAQCgAQGqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwjcrpXTutrpAhWOyYUKHSjJBkYQ4dUDCAw&uact=5

Then i'd add some filter words such as "court" or "portal" to narrow down more:

https://www.google.com/search?biw=1544&bih=828&sxsrf=ALeKk02dy20l4cQ8OiZavkcx6i50jl-bew%3A1590802972585&ei=HLrRXoekI46AjLsP6OeYoA8&q=court+portal+%22%C2%A9+2020+Tyler+Technologies%2C+Inc.%22+-site%3Atylertech.com&oq=court+portal+%22%C2%A9+2020+Tyler+Technologies%2C+Inc.%22+-site%3Atylertech.com&gs_lcp=CgZwc3ktYWIQDFAAWABg8kBoAHAAeACAAQCIAQCSAQCYAQCqAQdnd3Mtd2l6&sclient=psy-ab&ved=0ahUKEwiHotrwutrpAhUOAGMBHegzBvQQ4dUDCAw

**Comment by salter31** [comment]
I know that this isn't the place for coordinating tasks but I have a scrawler almost ready for Indiana which uses Tyler Technologies. I did it in golang since that my favorite language and I didn't see the python decision before I started. The concepts should be easy to translate later when re-doing it though. I will make the PR after the license stuff is sorted out and can put it in the correct place.

**Comment by Lokesh1411** [comment]
Hi everyone, I'm new to this repository, i need to know what we have to do and other. Please help and suggest !

**Comment by daiboz84** [comment]
I'm new to this .how is my phone being cloned

**Comment by salter31** [comment]
I realized after some work that the scraper that it is against their ToS to pull data with any form of a scaper so I won't be posting the work until we get the licensing/legal clearance that it is ok for whoever wants to actually run it. Specifically IN prevents any company in a contract providing the IT service of exposing data to allow scraping of the data.

`When retrieving information from MyCase, you are prohibited from (1) using or attempting to use spiders, robots, avatars, intelligent agents, or any other extraction or navigation search except for a normal browser; (2) aggregating, copying or duplicating any of the materials or information available from the site except for the small amount of materials and information temporarily required for an ordinary single use of the site;`

Plus there is no officer information exposed in the site so the data wouldn't be useful for a per officer analysis anyway. Seems to me like the best way to get the data from them is to ask for it from the state and get the complete records.
