### ISSUE TITLE
Alameda County Courts Link

### ISSUE THREAD

**Issue by rjeb** [Police-Data-Accessibility-Project/planning#64]
For anyone looking at scraping the court records for Alameda County, CA: it seems the link on the spreadsheet is only for civil trials which I am assuming we are ignoring. Criminal trials are available at: https://publicportal.alameda.courts.ca.gov/publicportal/ and they seem impossible to scrap by day.

Currently I think the best option is to go:
 **Search Hearings > Search type = Judicial Officer;  Go through all cases under each individual officer in the drop-down from 2005(oldest available record) to present**

This only provides case numbers though which we will have to plug back into their "smart search" to actually get case data from. These case records **DO NOT** contain any information about the arresting officer so I don't know if it is even worth scrapping.

**Comment by OscarVanL** [comment]
Is it possible the case records have PDF attachments (maybe in a section titled dockets)? In a portal I scraped it does not have the arresting officer and some other fields on the portal itself, but the PDF attachments for the case filing does have this information.

**Comment by rjeb** [comment]
Unfortunately it looks like such documents are unavailable in this portal. 
Looking at this website: http://www.alameda.courts.ca.gov/Pages.aspx/Court-Records-1-, it seems they have said the following: 

- "Public access does not include access to documents. "
- "Copies of non-confidential criminal case documents may be ordered online through the Criminal Record Requests portal. The copies will be mailed or emailed to you." In which case, it seems that they charge per page retrieved and only provide physical copies for documents > 10 pages.

A promising alternative is this site: https://www.acgov.org/sheriff_app/docket/docketSearch.do. Which provides "docket" information! The issues with this approach is that it only provides data for future hearings, and you can only search via docket number or police report number which aren't provided by the previous portal either. 

They really got to make it so hard...

**Comment by OscarVanL** [comment]
That's a shame. I think this is a situation we're going to encounter a lot. Different states have different accessibility for these documents. We'll just have to make do with what we can.

**Comment by ktynski** [comment]
It would be great to start documenting counties that we cant get this info from. (either because they don't have it, or because they make it impossible to scrape). There is work to be done applying public pressure to these counties, and with a good list of all failing at it, we will have a good shot at calling them all out for this failure.

**Comment by OscarVanL** [comment]
Great idea, a name-and-shame list of portals we've decided can't be scraped (and the reasons why) would be good. I could add this as an extra Sheet on our shared Google Sheets?

**Comment by ktynski** [comment]
That would be perfect. Thanks Oscar!
