### ISSUE TITLE
Containerize scraper using docker

### ISSUE THREAD

**Issue by nathanmentley** [Police-Data-Accessibility-Project/planning#76]
As a developer, it would be ideal if I could easily spin up different scrapers using a common interface so we can easily test and deploy each scraper in a common way.

One possible path to accomplish this is to use docker and build deployable containers. This will allow a CI system to quickly build and test scrapers without needing to know specific details about each one.

Each container will need to install the specific dependencies for each scrapper.

The biggest challenge will be setting up the browsers in a headless manner. As of today the node scraper uses puppeteer with chrome, and the python scrapper uses selenium with firefox.

**Comment by nathanmentley** [comment]
Just a heads up, I've started working on this, but I don't believe I have permissions to assign myself to the issue.

**Comment by mcsaucy** [comment]
The python scraper works well with a Xvfb, assuming no user input (like Captcha solving) is required. Not sure about the Node one.

**Comment by skoold2003** [comment]
I built a Node scraper for Craigslist a couple of years ago and didn't need a headless browser. As @mcsaucy mentioned it's only needed if there is some javascript action or a captcha wall to access the data. We should probably wait to find out what the data will look like before deciding what we'll need.

**Comment by dtoboggan** [comment]
I have a PR up for dockerizing the python/benchmark scraper here:

https://github.com/Police-Data-Accessibility-Project/Police-Data-Accessibility-Project/pull/101

Apologies @nathanmentley I didn't know you were working on it until I finished. I added you as a collaborator if you'd like to merge any of your work into mine.

**Comment by nathanmentley** [comment]
@dtoboggan, No worries I got caught up and was taking awhile. This PR is great.

One thing I have locally is that I'm using the ENTRYPOINT definition in my dockerfile so you can call:

docker run {imagename} {scraper args}

Instead of spinning up bash to call the docker file.

I don't know how that'll translate to docker-compose, tho. In my dockerfile I'm using Xvfb in the container so we can run FF inside the container. So compose isn't really needed.

Here is my WIP dockerfile: https://github.com/nathanmentley/Police-Data-Accessibility-Project/blob/task/issue-76-docker/Counties/Florida/Bay%20County/Scraper/dockerfile

I was envisioning someone calling something like this:

docker run -v {outputdir}:{outputdir} {imageName} --output={outputdir}/{outputfile} --solve-captcha

And if all the scrapers were setup with the same basic arguments you should just need to swap the image name and things should have a pretty standard interface to run.

However, if there is a good way to use compose to achieve that in a similar way that sounds great.

**Comment by mcsaucy** [comment]
It's seeming like we may be running multiple scrapers at once on a single host. Would #101 handle that well?
