### ISSUE TITLE
Add wiki page for meeting transcription, highlights and chat logs; organized by date and topic

### ISSUE THREAD

**Issue by jlintag** [Police-Data-Accessibility-Project/planning#87]
https://policeaccessibility.slack.com/archives/C014C0S31A9/p1590889096146300
https://policeaccessibility.slack.com/archives/C014C0S31A9/p1591108093268800
https://policeaccessibility.slack.com/archives/C014C0S31A9/p1591311241475600

**Comment by nicholastmosher** [comment]
Some of the links you've posted have media attachments. Are we trying to embed these audio and video clips into the wiki pages? I wonder whether we can commit those files directly into the wiki repository. Should theoretically be possible but I haven't tried it.

Is this issue focused on the clips themselves or the transcripts? If they're about the transcripts, I'd be happy to format them and include them in the wiki if they're already written up, but I don't have enough time to watch all of these clips and make the transcripts myself.

**Comment by jlintag** [comment]
Definitely don't transcribe things yourself; whatever text is available for the links provided should be what goes in the wiki.

Also, don't feel like you have to do everything yourself. If you can rope someone in to help, that'd be best
